### ISSUE TITLE
Error de ejecución Foxtabs.app

### ISSUE THREAD

**Issue by danielcastiblancom** [VFPX/FoxTabs#2]
Class definition MSXML2.DOMDOCUMENT.4.O is not found
OXMLDOM is not an object

**Comment by JoelLeach** [comment]
FoxTabs makes use of MSXML 4.0 for storing configuration.  VFP uses it as well for XMLAdapter (and MSXML 3 for XMLToCursor()).  It is not preinstalled with newer operating systems.  The current download location is https://www.microsoft.com/en-us/download/details.aspx?id=15697

**Comment by danielcastiblancom** [comment]
Thank you very much for your reply.
With the installation of the suggested software, the problem has been
fixed.
Thanks for your support. Blessings.
